### ISSUE TITLE
Test a case with type [u8;48]

### ISSUE THREAD

**Issue by Lanjiejie** [bitrocks/verifiable-secret-sharing#1]
I have tested an case with type [u8;48] in sample_sss scheme, but it came out a wrong result. And it is right when use the case with type [u8; 32]. The share_amount is set to 5, and threshold is set to 3. I can't find out the reason. Could you tell me why?

**Comment by bitrocks** [comment]
Would you elaborate more on your test cases?

**Comment by Lanjiejie** [comment]
Thanks for your comment! I have solved the problem. The reason is that the prime must be set to a larger number than secret. I tested a wrong case.
